set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
create_clock -period 10.000 -name clk -waveform {0.000 5.000}   [get_ports system_clk]

set_property PACKAGE_PIN T18 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]

set_property PACKAGE_PIN W7 [get_ports {digit_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {digit_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {digit_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {digit_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {digit_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {digit_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {digit_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[6]}]
set_property PACKAGE_PIN V7 [get_ports {digit_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_out[7]}]


set_property PACKAGE_PIN U2 [get_ports {digit_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[3]}]


#LED-Lights
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]

