# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/SortData/SortData.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SortData || ORIG_REF_NAME==SortData} -quiet] -quiet

# IP: bd/SortData/ip/SortData_dist_mem_gen_0_0/SortData_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SortData_dist_mem_gen_0_0 || ORIG_REF_NAME==SortData_dist_mem_gen_0_0} -quiet] -quiet

# XDC: bd/SortData/ip/SortData_dist_mem_gen_0_0/SortData_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/SortData/SortData_ooc.xdc
